baseURL = "https://deliciousreverie.co.uk/"
languageCode = "en-gb"
title = "Delicious Reverie"
theme = "deliciousreverie-v2"

# color-codes for highlighting derived from this style
pygmentsStyle= "monokai"
PygmentsCodeFences = true
pygmentsuseclasses = false

[params]
  description = "blog of developer, writer & bookworm benjamin read"
  author = "Benjamin Read"

defaultContentLanguage = "en"

[languages.en]
weight = 0
languageName = "English"

# Main menu
[[languages.en.menu.main]]
url    = "/"
name   = "Home"
weight = 1

[[languages.en.menu.main]]
url    = "/about"
name   = "About"
weight = 2

[[languages.en.menu.main]]
url    = "/links"
name   = "Links"
weight = 3

[[languages.en.menu.main]]
url    = "/contact"
name   = "Contact"
weight = 4
