baseURL = ""
languageCode = "en-gb"
title = "deliciousreverie"
theme = "deliciousreverie"

# color-codes for highlighting derived from this style
pygmentsStyle= "monokai"
PygmentsCodeFences = true
pygmentsuseclasses = false

[params]
  description = "blog of frontend designer benjamin read"
  author = "Benjamin Read"

defaultContentLanguage = "en"

[languages.en]
weight = 0
languageName = "English"

# Main menu
[[languages.en.menu.main]]
url    = "/"
name   = "Home"
weight = 1

[[languages.en.menu.main]]
url    = "/about"
name   = "About"
weight = 2

[[languages.en.menu.main]]
url    = "/portfolio"
name   = "Portfolio"
weight = 3

[[languages.en.menu.main]]
url    = "/blog"
name   = "Blog"
weight = 4