name = "Hugo Bootstrap4"
license = "MIT"
licenselink = "https://github.com/mmrath/hugo-bootstrap/LICENSE.md"
description = "A hugo theme using bootstrap 4, bootswatch, font-awesome, highlight.js"
homepage = "https://github.com/mmrath/hugo-bootstrap"
tags = ["blog", "technical", "personal"]
features = ["blog", "technical", "personal"]
min_version = 0.20.1

[author]
    name = "Murali Rath"
    homepage = "http://mmrath.com"
